Adjustments for API changes in ICE handshake behaviour
membraneframework/membrane_dtls_plugin pull request #5
Opened 2021-03-08 15:26 UTC by mickel8

related with:
membraneframework/membrane_ice_plugin#21
membraneframework/ex_dtls#8

2021-03-18 17:00 UTC, mat-hek requested changes

2021-03-18 17:00 UTC, mat-hek commented on lib/handshake.ex
> +    19 < head and head < 64 and byte_size(packet) >= 13
```suggestion
    head in 20..63 and byte_size(packet) >= 13
```

2021-03-18 17:00 UTC, mat-hek commented on lib/handshake.ex
> +  def init(id, parent, opts) do
it seems the new arguments are never used

2021-03-18 17:09 UTC, mickel8 commented on lib/handshake.ex
> +  def init(id, parent, opts) do
Yeah, they are prepared for future retransmissions support. We will use them to send `{:retransmit, id, packet}` message to ICE

2021-03-19 11:23 UTC, mat-hek commented on lib/handshake.ex
> +  def init(id, parent, opts) do
then just ignore them for now

2021-03-19 12:18 UTC, mat-hek approved these changes

2021-03-19 12:19 UTC, merged